### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by wkentdag** [rooftopcms/rooftop-cms#25]
Hi, I ran into a handful of issues when trying to spin up my own version of rooftop. I worked past issue #22 but still couldn't get things running. I'm pretty unfamiliar with vagrant so I'm assuming that I probably just missed a basic setup step somewhere - any pointers would be appreciated. Once I can get this up and running I'd be happy to submit a PR with updated documentation and/or code.
#### Installation steps
- install vagrant (`1.8.4`)
- install virtualbox (`5.0.22`)

``` shell
$ brew install homebrew/php/php55-pcntl
$ git clone https://github.com/rooftopcms/VVV.git
$ cd VVV/www/
$ git clone https://github.com/rooftopcms/rooftop-cms.git
$ composer install -d rooftop-cms/public/
-bash: composer: command not found
```
- installed composer following instructions from their [site](https://getcomposer.org/download/), but then ran into issue #22, which I bypassed by removing [composer.json:111-114](https://github.com/rooftopcms/rooftop-cms/blob/master/public/composer.json#L111-L114) and [140](https://github.com/rooftopcms/rooftop-cms/blob/master/public/composer.json#L140)

To update the composer lock file I ran `$ php composer.phar update -d rooftop-cms/public/`, which continued to fail until I had made the following changes to composer.json:
- change line 41 to use https (http fails ): (`"url": "https://wpackagist.org"`) 
- change line 136 to use any version over 0.3.4 rather than specifying explicitly (package wasn't available) : `"wpackagist-plugin/amazon-web-services": "^0.3.4",`

Finally, I ran `vagrant up` which took awhile but seemed to work fine - I could ssh into the box afterwards and everything. But when I point my browser to `http://rooftop-cms.dev` there doesn't seem to be anything there. I'm too naive about the tools involved to know where to turn next, but here's some guesses I had:
- there were some error messages during the `vagrant up` command suggesting that mysql wasn't configured properly - are there additional DB settings that I need to configure (maybe `.env`) ?
- am I in the wrong directory? all of these commands were executed inside the `/www` folder but there's a Vagrantfile at `VVV/`'s root ...?
- is there another config step involved to have the virtual box intercept the http request to `rooftop-cms.dev` - not really sure how this works
- are there any other basic configuration steps needed with virtualbox or vagrant that a first-time user would need to set up to get this working?

**Comment by edtjones** [comment]
Thanks SO much for this detail @wkentdag  - will get into this ASAP. In the meantime I'm setting up a test account on our Rooftop stack so you can have a play.

**Comment by hhsnopek** [comment]
@edtjones any luck? I'm having the same install errors locally

**Comment by edtjones** [comment]
@hhsnopek sorry about this. @foxpaul and I are working on this next week and I'll update this ticket. Are you on Gitter? Maybe we could chat there? https://gitter.im/rooftopcms/rooftop-cms

**Comment by PBruk** [comment]
@edtjones any luck with this? I spent all night trying to get this up and running but like @wkentdag, once I pointed to `http://rooftop-cms.dev` there was nothing there... I tried checking for progress via the Gitter channel, but... nada. I think I saw somewhere it was suggested adding to vvv-hosts file but that didn't work either.

**Comment by edtjones** [comment]
So sorry Phillip (sent you a personal note before I saw this issue) - I rebuilt my vagrant box from scratch and documented it here - https://rooftopcms.readme.io/docs/installing-a-development-environment

is that any help?

## 

Sent from my phone: please forgive the brevity.

Ed Jones
0779 187 4282

**Comment by wkentdag** [comment]
@edtjones those docs look great 👀  sorry for my radio silence on this issue, going to give it another go today

**Comment by edtjones** [comment]
Brill @wkentdag - please let me know how you get on. We are focussing on features at the moment hence not having spent as much time as we would like on the dev environment. Hope it works ok for you now.

## 

Sent from my phone: please forgive the brevity.

Ed Jones
0779 187 4282

**Comment by edtjones** [comment]
I'm going to close this issue; the answer is probably to have a docker container to make things simpler in development
