### ISSUE TITLE
Suggestions: social media pixel and analytics snippet 

### ISSUE THREAD

**Issue by anacf** [rooftopcms/rooftop-cms#26]
It would be great to see conversion trackers available through RT - not just per page, but rather individual page elements.

**Comment by edtjones** [comment]
Hi @anacf - not sure I understand this. Rooftop doesn't understand or have any context of the site or application it's providing content for. What would be the purpose of the trackers?

**Comment by evolve2k** [comment]
@edtjones I think @anacf is referring to this:  [The Facebook Pixel](https://www.facebook.com/business/help/651294705016616)

**Comment by edtjones** [comment]
Not going to do this - it's something for the frontend client application to handle.
