### ISSUE TITLE
LICENSE and readme mismatch

### ISSUE THREAD

**Issue by briantschu** [rooftopcms/rooftop-cms#36]
The readme indicates this project is MIT licensed though the LICENSE file indicates it is GPL licensed. Could you please clarify?

**[README.MD](https://github.com/rooftopcms/rooftop-cms/blob/master/README.md#whats-the-licence-for-rooftop)**

> What's the licence for Rooftop?
> 
> This project is MIT licenced (see the LICENCE file in this repo), so if you want to host it yourself, you can.

**[LICENSE](https://github.com/rooftopcms/rooftop-cms/blob/master/LICENSE)**

> ```
>                GNU GENERAL PUBLIC LICENSE
> ```

**Comment by edtjones** [comment]
Hi Brian

Sorry - it's GPLv3. Will amend the readme. 

Ed

##
