### ISSUE TITLE
Send appropriate cache headers

### ISSUE THREAD

**Issue by edtjones** [rooftopcms/rooftop-cms#4]
At the moment the api doesn't deliver any cache headers. We need to fix that so interstitial caches do the right thing.

A new plugin needs to handle:
- etags for entities (and collections??)
- cache-control
- last-modified

This project (GPL3) has some code we can reuse, I expect: https://github.com/gnotaras/wordpress-add-headers

**Comment by phendrick** [comment]
Created a https://github.com/rooftopcms/rooftop-response-headers plugin
