### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by alexeybondarenko** [rooftopcms/rooftop-cms#46]
HI.

Do you have a Docker container for a Rooftop CMS?

**Comment by edtjones** [comment]
Hi @alexeybondarenko we don't - but it would be amazing! A PR with a dockerfile would be gratefully received :-)

**Comment by Snaver** [comment]
Hey @alexeybondarenko 

I played around with getting Docker support working with [roots/bedrock](https://github.com/roots/bedrock) which I believe rooftop is partially based on.

You can see what's required to get started in this commit https://github.com/Snaver/bedrock/commit/70f1a92cbe3bc01c2a2887b2b3965715f5f81d00, pretty simple.

Good luck!

**Comment by pranaypratyush** [comment]
Hi there, any further progress on this?
