### ISSUE TITLE
acf-repeater repo missing?

### ISSUE THREAD

**Issue by jalbstmeijer** [rooftopcms/rooftop-cms#49]
Hi,
I'm following the instructions here: https://rooftopcms.readme.io/docs/installing-a-development-environment

Is there not supposed to be an acf-repeater repo at https://bitbucket.org/errorstudio/ ?

Gr, J

**Comment by edtjones** [comment]
HI @jalbstmeijer - ACF repeater is a licenced add-on to ACF, which is why it's not public. Sorry - will add that to the docs. We are investigating a better way to use composer to avoid this sort of confusion.

For now, I suggest getting a hold of the acf repeater plugin and changing the composer.json to point to your version.

Ed

**Comment by jalbstmeijer** [comment]
> For now, I suggest getting a hold of the acf repeater plugin and changing the composer.json to point to your version.

And by that you mean?:

wget https://downloads.wordpress.org/plugin/advanced-custom-field-repeater-collapser.zip -O /tmp/advanced-custom-field-repeater-collapser.zip

cd public/web/app/mu-plugins/
unzip /tmp/advanced-custom-field-repeater-collapser.zip acf-repater.zip
mv advanced-custom-field-repeater-collapser acf-repater

**Comment by edtjones** [comment]
No, you need to licence the plugin here: https://www.advancedcustomfields.com/add-ons/repeater-field/

**Comment by jalbstmeijer** [comment]
Ok, and than extract it to VVV/www/rooftop-cms/public/web/app/mu-plugins/acf-repater ?
And than edit VVV/www/rooftop-cms/public/composer.json , what entry are you referring too?

only reference seems to be:
grep -i acf VVV/www/rooftop-cms/public/composer.json
    "rooftopcms/rooftop-acf-exposer": "~1.2.0",

**Comment by jalbstmeijer** [comment]
Is this acf-repater plugin needed? if not, how to proceed without it?
if needed, could you be more specific in how to proceed after buying the licence?
Especially on your remark "and changing the composer.json to point to your version"

**Comment by edtjones** [comment]
Hi @jalbstmeijer what I would do is:

* buy the plugin
* put in a private repo
* add that private repo and the plugin to your composer.json so it's installed from your repo

Hope that helps?

The acf-exposer plugin SHOULD still work without the acf repeater plugin but we haven't tested that configuration.

Ed

**Comment by jalbstmeijer** [comment]
Thanks.

Like mentioned earlier,  VVV/www/rooftop-cms/public/composer.json does not mention acf-repater
You mean VVV/www/rooftop-cms/.gitmodules?
