### ISSUE TITLE
_embed GET querystring breaks API responses

### ISSUE THREAD

**Issue by edtjones** [rooftopcms/rooftop-cms#6]
According to [these docs](http://v2.wp-api.org/extending/linking/) we should be able to automatically embed relations into a response by passing `_embed` as a GET querystring.

But when we do, we get an error in the REST API plugin:

```
Fatal error: Cannot unset string offsets in /srv/www/rooftop-cms/public/web/app/mu-plugins/rest-api/lib/endpoints/class-wp-rest-controller.php on line 179
```

Interesting, this is an identical error to the one produced by #5

**Comment by phendrick** [comment]
resolved in the same fix as #5
